#!/usr/bin/env python
import argparse
import os
import sys
from screwdriver.util import read_json
from screwdriver.screwdriver import ScrewDriver

# Command line arguments
# ========

parser = argparse.ArgumentParser(description='Update the mothership.')

parser.add_argument('--update', '-u', action='store_const', dest="action", const="update", help='Update the whole project (pull and npm install).')
parser.add_argument('--install', '-i', action='store_const', dest="action", const="install", help='Just npm install.')
parser.add_argument('--checkout', action='store_const', dest="action", const="checkout", help='Checkout the module versions as specified in project.json.')
parser.add_argument('--pull', action='store_const', dest="action", const="pull", help='Pull the current branches from origin.')
parser.add_argument('argv', nargs='*', help='Arguments passed to the command.')

# Main
# ========

args = vars(parser.parse_args())

action = args['action']
root_dir = os.path.realpath(os.getcwd())

screwDriver = ScrewDriver(root_dir)
method = getattr(screwDriver, action)
method(args)
